### ISSUE TITLE
 Invalid V8 thread access

### ISSUE THREAD

**Issue by jdin** [ing-bank/baker#54] opened 2017-10-19 14:59 UTC
Hi Baker team!

I have just tried the latest release of Baker (1.1.14) and have noticed one issue with `CompiledRecipe::getVisualRecipeAsSVG` method. It looks like that because of graphviz-java this method can only be called from a single thread otherwise an exception is thrown:
```
java.lang.Error: Invalid V8 thread access
                at com.eclipsesource.v8.V8Locker.checkThread(V8Locker.java:56)
                at com.eclipsesource.v8.V8.checkThread(V8.java:676)
                at com.eclipsesource.v8.V8.executeStringScript(V8.java:499)
                at com.eclipsesource.v8.V8.executeStringScript(V8.java:483)
...
```
For now the workaround is to use smth like singlethreadexecutor and always call this method using it. But of course it would be nicer if you can handle it.

Kind regards,
Sergey

PS: [Here](https://github.com/eclipsesource/J2V8/issues/33) you can find some more information about this exception.

**Comment by merlijn** [comment] 2017-10-19 15:04
Hi Sergey, Thanks for the issue :) We will pick this up for the next 1.1.x release.

**Comment by merlijn** [comment] 2017-10-20 09:47
I cannot reproduce this, the following runs fine (on a non single threaded execution context):

```scala
  val recipe = ...
  val futures = (1 to 100).map(_ => Future { recipe.getVisualRecipeAsSVG })
  val svgs = Await.result(Future.sequence(futures), 10 seconds)
```

Maybe depends on environment again. Will try on a windows machine when I get the chance.

**Comment by merlijn** [comment] 2017-10-20 10:35
As another workaround you can use: 

```java
Graphviz.useEngine(new GraphvizJdkEngine());
```

 This should use the JDK's Nashorn javascript engine, which should be thread safe. The downside is that it is much slower to generate the SVG.

**Comment by merlijn** [comment] 2017-10-20 12:18
@jdin 

And using: ```Graphviz.useEngine(new GraphvizJdkEngine());``` 
Does it still break?

**Comment by jdin** [comment] 2017-10-20 12:32
If I add this line `Graphviz.useEngine(new GraphvizJdkEngine());` then it works. And indeed it is slower. I think I will continue to use singlethreadexecutor for now and then it works without problem.

**Comment by merlijn** [comment] 2017-10-23 10:02
I don't see how we really solve this nicely for all environments.

I am proposing removing this as a feature from Baker and letting the library user implement this if they wish. It is only 3 lines of code and 1 dependency.

What we can do is document in the README how the SVG can be generated and what problems might arise if you use V8.

**Comment by jdin** [comment] 2017-10-23 15:08
It is fine for me. Indeed it is only a couple of lines and you have 2 choices: you can use java version or you can use javascript version to generate SVG.

**Comment by bekiroguz** [comment] 2017-12-21 15:00
As mentioned by Merlijn, this feature is removed from Baker so I am closing this bug.

**Closed by bekiroguz** 2017-12-21 15:00 UTC
Labels: bug
